### ISSUE TITLE
Remove last method from stack trace

### ISSUE THREAD

**Issue by KristianWedberg** [AArnott/Validation#11]
Using all these methods adds the methods to the exception stack trace, which is undesirable since the developer always wants to get to the method that called Requires.NotNull() etc. 

Is there any way to automatically strip out the unwanted last stack frame from the stack trace?

**Comment by AArnott** [comment]
Not that I know of. The callstack printed in an exception is true. You'll have to look past the Requires class that throws to the next one to know the relevant method. 
But even if we could hide the Requires method in the callstack, when a method throws in its argument validation section, the fault isn't there -- it's in its caller. So you still have to mentally skip over to the next frame. So I don't see hiding Requires itself as really solving the problem. It just removes one of two frames you still have to mentally skip.
