### ISSUE TITLE
Add support for .NETStandard

### ISSUE THREAD

**Issue by Nimgoble** [AArnott/Validation#13]
Please add support for .NETStandard.  I'm trying to use PCLCrypto with a .NETStandard library and it isn't working because Validation isn't compatible with any .NETStandard version.

**Comment by AArnott** [comment]
Validation works with .NETStandard if you add an `imports` property to your frameworks.
[PCLCrypto doesn't work with Linux or OSX](https://github.com/AArnott/PCLCrypto/issues/103) just FYI.

We'll keep this issue active to track supporting .NetStandard more completely by adding a lib/netstandard folder to the package.

**Comment by Nimgoble** [comment]
Hey Andrew, does that mean that PCLCrypto won't work on Android and iOS?  Forgive my ignorance, I'm not sure what the differences between OSX and iOS are.

**Comment by AArnott** [comment]
PCLCrypto works great on Android and iPhone. OSX runs Mac whereas iOS runs iPhone. 
So pclcrypto works great on mobile platforms, but not on Mac and Linux desktop machines.
