### ISSUE TITLE
Cannot upgrade PCL reference to 2.3.5

### ISSUE THREAD

**Issue by InquisitorJax** [AArnott/Validation#16]
"Could not install package 'System.Diagnostics.Debug 4.0.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile7', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."

got when upgrading PCL reference from 2.2.8 to 2.3.5.

**Comment by AArnott** [comment]
What version of VS and/or nuget are you using?

**Comment by InquisitorJax** [comment]
VS Update 3 + Nuget latest (3.4.4 I think)

**Comment by AArnott** [comment]
Thanks. I'll look into it.

**Comment by Kornelis** [comment]
Hi Andrew,

have the same Problem when updating the Lib on an PCL Project with a differnt profile "Could not install package 'System.Diagnostics.Debug 4.0.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."  Also using VS 2015 Update 3 + Nuget 3.4.4.1321.

Thanks in advantage and kind regards

Kornelis
