### ISSUE TITLE
visual studio 2015 - nuget can't update from 2.3.7

### ISSUE THREAD

**Issue by manhao-chen** [AArnott/Validation#20]
hi there, 

i'm trying to update my portable class project

currently its using 
<package id="Validation" version="2.3.7" targetFramework="portable45-net45+win8" />

i'm trying to upgrade it to 2.4.9 but get an error of 
Could not install package 'System.Runtime.InteropServices.RuntimeInformation 4.0.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile7', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

any ideas?

**Comment by AArnott** [comment]
Can you try upgrading the version of the NuGet Package Manager extension itself in Visual Studio?

**Comment by AArnott** [comment]
Never mind. I just tried it with 3.4.4.1321 which appears to be the latest for VS2015 and it failed to install, after installing dozens of extra facade packages from the new .NET surface area.

Clearly this is a regression for PCL libraries. The latest you can use is 2.3.7 unless we re-add explicit support for PCL libraries to this package, which I'll keep this issue active to track. 

Incidentally, you may want to consider targeting .netstandard, as shown below. After doing so, the Validation package installs quickly and correctly.
![image](https://cloud.githubusercontent.com/assets/3548/23332494/69c7f174-fb2f-11e6-8dfe-55b5b2c3442b.png)

**Comment by manhao-chen** [comment]
I'm using pclcrypto and need a project that is a portable library for supporting all platforms

**Comment by AArnott** [comment]
understood. I'm making progress on bringing back PCL support. Hope to have it by end of day.

**Comment by AArnott** [comment]
Thank you for your bug report. 
You should be able to upgrade to 2.4.10. Please confirm

**Comment by manhao-chen** [comment]
just tested, works beautiful !!
