### ISSUE TITLE
Validation.dll does not have a NeutralResourcesLanguageAttribute on it

### ISSUE THREAD

**Issue by paulanthonymorris** [AArnott/Validation#22]
Am getting this now having updated UWP project to 2.4.10:
...\.nuget\packages\Validation\2.4.10\lib\netstandard1.3\Validation.dll : warning MSB3817: The assembly "...\.nuget\packages\Validation\2.4.10\lib\netstandard1.3\Validation.dll" does not have a NeutralResourcesLanguageAttribute on it. To be used in an app package, portable libraries must define a NeutralResourcesLanguageAttribute on their main assembly (ie, the one containing code, not a satellite assembly).

When running unit tests that assert exceptions that Validation throws I now get these failures:
Result Message:	
Assert.Throws() Failure
Expected: typeof(System.ArgumentException)
Actual:   typeof(System.Resources.MissingManifestResourceException): Unable to load resources for resource file "Validation.Strings" in package "8c4135be-e11e-423c-829b-76933c7da27f".

**Comment by AArnott** [comment]
Thanks for the report. This is fixed in the latest version.

**Comment by paulanthonymorris** [comment]
Thanks for the quick response Andrew.
