### ISSUE TITLE
Export Control Classification Number

### ISSUE THREAD

**Issue by DJ-11** [AArnott/Validation#26]
Hi, 

Our team would like to use/include your software in our products, and reexport them from Japan.
So, could you provide us the Export Classification Control Number(ECCN) information of your software?

If you do not have your software classified with an ECCN, please kindly answer the following questions so that we may self-classify:

Q1. Does the software perform any encryption or utilize any encryption processes? Yes/No

Q2. In case that the answer to Q1 is Yes, please indicate whether you notified BIS and ENC Encryption Request Coordinator via email of the Internet location (e.g., URL or Internet address) of your publicly available encryption source code.
Or please indicate whether you provided each of them a copy of your publicly available encryption source code or not. 

Thank you in advance for your cooperation.
Regards,

**Comment by AArnott** [comment]
This library contains no encryption. This library does not have an ECCN independent of Visual Studio, so please self-classify.
