### ISSUE TITLE
Adding a NotDefault<T> for structs

### ISSUE THREAD

**Issue by AndreiCsibi-msft** [AArnott/Validation#28]
What do you think about adding a ```Requires.NotDefault<T>``` for enums?
For example enums with values ```None```/```Unknown```=0 or numbers with default values might not be allowed as parameter values.

**Comment by AArnott** [comment]
An interesting idea. Would we rely on a struct accurately overriding `Equals` to determine if two instances are different? Or would we do a straight-up zero memory check somehow?

**Comment by AndreiCsibi-msft** [comment]
We'd rely on the struct to implement Equals correctly because that's the recommended practice anyway for value types (see [ValuesType.Equals documentation](https://docs.microsoft.com/en-us/dotnet/api/system.valuetype.equals?redirectedfrom=MSDN&view=netframework-4.7.2#System_ValueType_Equals_System_Object_)).
