### ISSUE TITLE
Enhance the validations to be more fluent

### ISSUE THREAD

**Issue by mwpowellhtx** [AArnott/Validation#30]
For instance, I would like to do things such as this:

```C#
public static class Assumes
{
    public static T Is<T>(object value)
    {
       True(value is T);
        return (T) value;
    }
}
```

**Comment by mwpowellhtx** [comment]
Or, for that matter:

```C#
public static T AssumeIs<T>(this object value)
{
   True(value is T);
    return (T) value;
}
```

**Comment by AArnott** [comment]
This would result in an `InternalErrorException` thrown that doesn't have a message that explains the problem. Simply using a cast (and a null check) would cause a more specific `InvalidCastException` that explains the actual and expected types. Wouldn't that be better?

**Comment by mwpowellhtx** [comment]
Indeed that would be better.
