### ISSUE TITLE
How can a Type not be Requires Defined

### ISSUE THREAD

**Issue by mwpowellhtx** [AArnott/Validation#31]
When you pass a ``value`` to ``Requires.Defined<T>(...)``, how is it that ``T`` cannot be *defined*? I mean, I suppose you could pass a *struct* value that implements the interfaces ``IComparable``, ``IFormattable``, and sometimes ``IConvertible``, depending on your *dotnet* API surface area, that is *not* an ``enum``, but why would you do that? Is this something that is useful for, say, ``FlagsAttribute`` ``enum`` types?

**Comment by mwpowellhtx** [comment]
I think I see, considering a case something like this, a defined ``enum``:

```C#
private enum Fruit
{
    Apples = 1,
    Oranges
}
```

And a call like this:

```C#
Requires.Defined((Fruit) 0, ArgumentName); // Would throw ArgumentException.
```

**Comment by AArnott** [comment]
Exactly. This method is specifically for enum types. But `enum` is not a valid generic type constraint, so we constrain on interfaces that we know enums implicitly implement.

**Comment by mwpowellhtx** [comment]
I understand that, i.e. ``enums`` are ``structs``, naturally which implement some interfaces, however, not all, depending on the API surface area. Appreciate the [insight concerning API surface areas](/AArnott/Validation/issues/32), did not know that re: the profiles. I'm assuming these are a bit mask defined somewhere, or something analog to that, if I chose to dig further.

**Comment by AArnott** [comment]
> I'm assuming these are a bit mask defined somewhere, or something analog to that, if I chose to dig further.

One might think so (I expected it at first too). But no. It's just a table that the .NET team generated one day for a bunch of combinations and assigned ordinal values to each one. No one bit represents a particular platform or anything sensible like that.
