### ISSUE TITLE
Verify.NotDisposed ambiguous or misleading parameter names

### ISSUE THREAD

**Issue by mwpowellhtx** [AArnott/Validation#33]
In `Verify.NotDisposed(bool condition, string message)`, `string message` does not appear to be a *message* at all, but rather an *object name*, at least according to the error:

```
Cannot access a disposed object.
Object name: '...'
```

Reporting only the leading indicator, smoke test if you will. Review comprehensively for the extent of the issue.

**Comment by mwpowellhtx** [comment]
My assessment would be that the exception messages seem inconsistent at best.

**Comment by AArnott** [comment]
It appears to only be that specific overload that was faulty. Fixed in #40.
