### ISSUE TITLE
Any plan to support DotNetCore/ASPNET Core as well

### ISSUE THREAD

**Issue by vamboda** [AArnott/Validation#35]
Hi
I am wondering if there is any plan to port this library in Dot Net Core?

**Comment by AArnott** [comment]
Not really. This library is mostly deprecated in favor of Microsoft.VisualStudio.Validation. It does netcoreapp already.

**Comment by KamranShahid** [comment]
> Not really. This library is mostly deprecated in favor of Microsoft.VisualStudio.Validation. It does netcoreapp already.
For avoiding  Microsoft.VisualStudio.Validation i am moved here. Problem with it is during publish option(e,g, .net core 3.1 with linux as target) above library generate so many resource folder. which is annoying

**Comment by AArnott** [comment]
So write a script to delete the satellite assemblies I guess. Offering localized translations of error messages is a feature.

**Comment by KamranShahid** [comment]
At the moment just using following two option for publishing on my main application project

dotnet publish -c release -r linux-x64   (for linux server deployments)

dotnet publish -c release -r win-x64     (for windows server deployments)

Can you give give some hint where and what type of script should i add in my csproj?

**Comment by AArnott** [comment]
Well first just to be clear, are you *intentionally* scoping your application to just one language? If not, you should know that these extra sub-directories are providing your application with multi-lingual support.

Secondly, I have no idea what to add to a csproj to suppress copying of satellite assemblies to the publish output. There very well may be a way, but I've personally never wanted to remove (even partial) multi-lingual support before so I haven't researched it.

**Comment by KamranShahid** [comment]
> Well first just to be clear, are you _intentionally_ scoping your application to just one language? If not, you should know that these extra sub-directories are providing your application with multi-lingual support.
> 
> Secondly, I have no idea what to add to a csproj to suppress copying of satellite assemblies to the publish output. There very well may be a way, but I've personally never wanted to remove (even partial) multi-lingual support before so I haven't researched it.

My application is basically a backend webapi. Nothing in my mind where i would need this multilingual support in my app.
