### ISSUE TITLE
Issues with package id

### ISSUE THREAD

**Issue by RachelDavids** [AArnott/Validation#37]
Came across this today. Created my standalone (not a package) csproj called "Validation" several months ago. Today I tried to include "PInvoke.User32" - this has a dependency on a package called "Validation". How am I, as a developer, supposed to know that I should not have used "Validation" for my project name.

See also [https://github.com/NuGet/Home/issues/6754](https://github.com/NuGet/Home/issues/6754)

**Comment by AArnott** [comment]
Well, I don't know that you can know in advance. But when the error hits you, you can either rename your project/assembly, or at least rename your "package". Even if you don't create a package out of your Validation project, it has a presumed ID that is colliding.

I think if you add `<PackageId>MyValidationPackage</PackageId>` to your project file as a property, it will 'break the loop' and unblock you.
