### ISSUE TITLE
Freshen this repo up

### ISSUE THREAD

**Issue by AArnott** [AArnott/Validation#38]
This repo hasn't been updated for a while, and is used by some popular packages.

Let's get it up to date with the latest stuff from its cousin Microsoft.VisualStudio.Validation.

**Comment by scottdorman** [comment]
Having just stumbled across it's cousin, why have (and maintain) both libraries? Outside of the fact that Microsoft.VisualStudio.Validation is newer (and mis-named since nothing in the code has anything to do with Visual Studio), wouldn't it be better to just merge the two (and maybe rename it)?

**Comment by AArnott** [comment]
I think renaming it would appear to create a 3rd one. I think the name `Validation` is ideal, but I don't think I can pull of deprecating either one in favor of the other because both are heavily used. 
I might at least make them as nearly identical in feature set as possible, but then... that's just extra work for me and if folks want more functionality they can switch to the MS.VS.Validation one which gets more attention.

So I'm divided.

**Comment by scottdorman** [comment]
Yes, it's definitely the ideal name. I guess what would be best is to somehow share the code between them to keep them in sync (a git submodule maybe?) although I'm not sure how that would realistically work.

Up until yesterday, I'd never heard of the MS.VS.Validation package so, to me at least, there is a discoverability issue for it.
