### ISSUE TITLE
Does Report.Method(...) work correctly? 

### ISSUE THREAD

**Issue by jafsuen** [AArnott/Validation#39]
Report.If(true, "some message");
            Report.If(false, "some message");
            Report.IfNot(true, "some message");
            Report.IfNot(false, "some message");
            Report.Fail("some message");
            Report.Fail();

It seems that Report.* have no any result.

**Comment by AArnott** [comment]
I'm afraid `Report` does *not* work (at all). It was a bug I found and fixed in Microsoft.VisualStudio.Validation, which is where most of my effort goes nowadays. Feel free to switch to that.

**Comment by AArnott** [comment]
Fixed in v2.5 by #40
