### ISSUE TITLE
Add `Requires.Is<T>` to match `Assumes.Is<T>`

### ISSUE THREAD

**Issue by scottdorman** [AArnott/Validation#42]
It would be convenient to have a `Requires.Is<T>` method, like `Assumes.Is<T>`. Also, does it make more sense for this to be named `IsType`, since that's really what it's testing?

**Comment by AArnott** [comment]
I wouldn't want to rename `Assumes.Is<T>`  since it's shared with the vs-validation repo's API. 

I'm curious why `Requires.Is<T>` would be better than just changing the parameter type to be `T`, which enforces it but in a way that is clear in the API. What do you have in mind?

**Comment by scottdorman** [comment]
> changing the parameter type to be `T`

I'm not sure I'm following here. 

In general, I think this would be helpful in scenarios where you need to test that a parameter of `object`, a generic type argument, or a parameter of `Type` is a specific type `T`. 

I  had a use case in mind initially, as I had an IsType<T> in my library that I'm returning, but I can't seem to find it any more. I may have replaced it with something else.

**Comment by AArnott** [comment]
> I'm not sure I'm following here.

I'm saying that if you have this method:

```cs
public void Foo(object o)
{
    Requires.Is<string>(o);
}
```

Would it not be preferable to change the method to this:

```cs
public void Foo(string o)
{
}
```

Now the caller knows you demand a `string`. Otherwise they may pass in `object` only to see a runtime exception thrown.

**Comment by scottdorman** [comment]
Yes, in that scenario it would probably make more sense to just change the parameter from `object` to `string`. I can't find the use case I had in mind for it anymore, so I'm good without this. If I come across it at some point, I can always reopen the issue.
