### ISSUE TITLE
XML doc comments

### ISSUE THREAD

**Issue by scottdorman** [AArnott/Validation#46]
There are a lot of places in the doc comments where it uses the syntax of `<c>null</c>` rather than `<see langword="null"/>`, or doesn't do anything and just uses plain text "null". Should these be updated to use the `<see langword="null"/>` syntax?

As an example, here is what the updated comment (for `Requires.NotNull<T>(T, string?)` would look like:
https://github.com/AArnott/Validation/blob/2378284a62d732a89454564afca189b48e7ba5ba/src/Validation/Requires.cs#L19-L26
```cs
/// <summary>
/// Throws an exception if the the specified parameter's value is <see langword="null" />.
/// </summary>
/// <typeparam name="T">The type of the parameter.</typeparam>
/// <param name="value">The value of the argument.</param>
/// <param name="parameterName">The name of the parameter to include in any thrown exception.</param>
/// <returns>The value of the parameter.</returns>
/// <exception cref="ArgumentNullException">Thrown if <paramref name="value"/> is <see langword="null" />.</exception>
```

**Comment by AArnott** [comment]
I would accept a PR that fixes this. 
But I'm curious why it matters.

**Comment by scottdorman** [comment]
It's a bit of nit, to be fair, but the `<see langword="null"/>` translates to `null reference (Nothing in Visual Basic)` as text. Really, this applies to `true` and `false` as well.

**Comment by AArnott** [comment]
Interesting. Thanks for the info.

**Comment by bjm-csse** [comment]
Hey Scott, I am interested in working on this! Would you assign this to me please? Thanks!

**Comment by scottdorman** [comment]
@bjm-csse That would be great! I don't have the ability to assign issues, but @AArnott can when he's able to.
