### ISSUE TITLE
Requires.NotEmpty(Guid)

### ISSUE THREAD

**Issue by scottdorman** [AArnott/Validation#49]
The `Requires.NotEmpty(Guid)` method here was replaced with `Requires.NotDefault`, which creates an inconsistency with  Microsoft.VisualStudio.Validation. Should we update that repo to match? This is tangentially related to #38.

**Comment by AArnott** [comment]
> The Requires.NotEmpty(Guid) method here was replaced

I can't find any evidence that that API used to be in this library. At least as of 2.4.22, it seems the Requires class didn't have that method. The vs-validation library _does_ define that method. 
Of the two, I prefer `NotDefault<T>` because it works for more parameter types. Are you proposing that we add `NotDefault<T>` to vs-validation or that we add `NotEmpty(Guid)` to _this_ repo?

**Comment by scottdorman** [comment]
Correct, `NotEmpty(Guid)` never existed here. I also prefer `NotDefault<T>`. I was thinking that `NotDefault<T>` should probably be added to vs-validation and have `NotEmpty(Guid)` be removed. I put the issue here as I wasn't sure which direction you might want it to go (vs-validation => here or here => vs-validation).

**Comment by AArnott** [comment]
> and have `NotEmpty(Guid)` be removed

That's never going to happen. vs-validation is used in many Microsoft components and thus has a high backward compat obligation.
I don't mind copying `NotDefault<T>` from here to vs-validation, but that's probably all I'd want to do.

**Comment by scottdorman** [comment]
As I was looking at vs-validation for the other PR, I noticed that it's not just `NotDefault<T>` which is missing. It's also missing `That`, `ValidState`, and the new `ValidElements<T>` methods. Should those get pulled in as well (along with their associated tests)?

**Comment by AArnott** [comment]
I'm in favor of copying the following to vs-validation: `ValidElements<T>`, `NotDefault<T>`.

Let us _not_ copy over `ValidState` (which is redundant with `Verify.Operation` which is the better API for it). We should `[Obsolete]` the `ValidState` API with a message telling folks to use `Verify.Operation` instead.

`That` is similarly redundant with `Requires.Argument` and should be deprecated. Having redundant methods for the sake of sounding "fluent" makes an API more confusing, IMO.

**Comment by scottdorman** [comment]
That all makes sense. I'll have a PR shortly for that. Should we also add `[Obsolete]` to `NotEmtpy(Guid)`?

**Comment by AArnott** [comment]
Let's leave NotEmpty(Guid) alone. It's in vs-validation and we won't be obsoleting it there.
