### ISSUE TITLE
Support modern PCLs (net46+dnxcore+uwp10)

### ISSUE THREAD

**Issue by AArnott** [AArnott/Validation#6]

**Comment by AArnott** [comment]
Re-opening. Although we now compile an assembly compatible with the new contract reference assemblies, we still lack a nuget package that advertises the fact such that a uwp10+dnxcore50+net46 targeted PCL will allow its installation.

**Comment by AArnott** [comment]
Even with a `lib\dotnet` folder in the nupkg and the appropriate dependencies expressed in the nuspec file, the new PCL reports incompatibility with [the package](https://onedrive.live.com/redir?resid=63D0C265F96E43D!2537454&authkey=!ANEtS33pHGB2XMM&ithint=file%2cnupkg).

I'll reach out for help resolving this.

**Comment by ericstj** [comment]
Can you share the compatibility error?

**Comment by AArnott** [comment]
Sure, @ericstj:

```
PM> install-package validation
Restoring packages for 'ClassLibrary2'.
Restoring packages for C:\Users\andrew\Documents\Visual Studio 2015\Projects\ClassLibrary2\ClassLibrary2\project.json...
install-package : Unable to resolve validation (≥ 2.2.3) for .NETPlatform,Version=v5.0.
At line:1 char:1
+ install-package validation
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Unknown Compatibility Profile: net46.app
Unknown Compatibility Profile: uwp.10.0.app
Unknown Compatibility Profile: dnxcore50.app
Package restore failed for 'ClassLibrary2'.
install-package : Package restore failed. Rolling back package changes for 'ClassLibrary2'.
At line:1 char:1
+ install-package validation
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
PM> 
```

**Comment by ericstj** [comment]
Looks to me like it isn't even downloading your package `validation`.  If it were, I'd expect to see "installing validation", "checking compatibility for..." same as you see in the output window during a restore.

Are you sure you have the package in a feed that is visible to nuget?

**Comment by AArnott** [comment]
It should be finding it. This is from VS, with a package source created that points to the directory that contains the .nupkg file and that source is selected when I try to install the package from the package manager console.
I have not created a nuget.config for this solution, however.

**Comment by AArnott** [comment]
When I add a nuget.config file, it works. Shouldn't this work without one? Does the VS nuget client configuration dialog not work for project.json?

**Comment by yishaigalatzer** [comment]
It should absolutely work. In fact that is how the settings dialog work, it updates nuget.config.

**Comment by AArnott** [comment]
@yishaigalatzer It doesn't seem to in this case anyway. I've never seen it create a nuget.config where none exists. For several projects, I've seen the settings dialog work for packages.config package restores but not project.json. Should I file a bug on nuget/home?

**Comment by yishaigalatzer** [comment]
It would never create a new one. It will update the global one.

It's awfully weird, because there is just one config system. My only guess would be caching.

So two thing to look for:

Does global nuget.config change?
Do things stay working after restarting vs?

Sent from my Windows Phone
________________________________

**Comment by AArnott** [comment]
Where is the global nuget.config file?
Restarting VS seems irrelevant because nuget restore at the command line fails as well.
