### ISSUE TITLE
No license specified

### ISSUE THREAD

**Issue by rsnitsch** [AArnott/Validation#8]
Please add a LICENSE file.

**Comment by AArnott** [comment]
Good catch. I'm working on adding the MIT license file now. It will be retroactively valid for all prior versions and releases from this project.

**Comment by AArnott** [comment]
Hmmm... it looks like it's already got a license link from the nuget package to the MS-PL. So I guess I'll stick with that one and just make it more discoverable. But if MIT is preferable, let me know.
