### ISSUE TITLE
Framework version 2.0

### ISSUE THREAD

**Issue by oghenez** [AArnott/Validation#88]
Hi,

Because of the massiveness of my project, upgrading outright to .NET 4.5 isn't feasible right now
Any compatible version for .net 2.0 or 3.5

Thanks

**Comment by AArnott** [comment]
There is not. But I just gave it a few minutes of effort and I can add such support.

**Comment by AArnott** [comment]
It turned out to take a little more than a few minutes. It turns out that `dotnet build` on linux doesn't support building libraries that include .resx files that target net35. But I switched to a Windows agent and made a few other changes to make it work and enhance tests a bit too.

**Comment by AArnott** [comment]
This will go out to nuget.org shortly as a 3.6-beta.
