### ISSUE TITLE
Add enum validation

### ISSUE THREAD

**Issue by Ilchert** [AArnott/Validation#9]
It will be very useful if you add Enum.IsDefined validation to validate a value, that is not defined in Enum and throw the InvalidEnumArgumentException.

**Comment by AArnott** [comment]
Interesting. I've never heard of that exception type but that sounds useful.

**Comment by Ilchert** [comment]
What about throws the [InvalidEnumArgumentException](https://msdn.microsoft.com/ru-ru/library/system.componentmodel.invalidenumargumentexception(v=vs.110).aspx)?

**Comment by AArnott** [comment]
That exception type isn't defined in either of the portable profiles that this project targets. So unless I add a new target platform (perhaps net45) I can't throw it.
